# Generated by Django 4.1.7 on 2023-02-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_ext_eight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_eight', to='core.bearingextended', verbose_name='Подшипник 8'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_ext_one',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_one', to='core.bearingextended', verbose_name='Подшипник 1'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_ext_seven',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_seven', to='core.bearingextended', verbose_name='Подшипник 7'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_ext_two',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_two', to='core.bearingextended', verbose_name='Подшипник 2'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_five',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_five', to='core.bearing', verbose_name='Подшипник 5'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_four',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_four', to='core.bearing', verbose_name='Подшипник 4'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_nine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_nine', to='core.bearing', verbose_name='Подшипник 9'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_six',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_six', to='core.bearing', verbose_name='Подшипник 6'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='bearing_three',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_three', to='core.bearing', verbose_name='Подшипник 3'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='cooler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.cooler', verbose_name='Охладитель'),
        ),
    ]
