# Generated by Django 4.1.7 on 2023-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exhauster_bearing_ext_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearing',
            name='temperature_alarm_max',
            field=models.IntegerField(null=True, verbose_name='Уставка аварийная (max)'),
        ),
        migrations.AlterField(
            model_name='bearing',
            name='temperature_alarm_min',
            field=models.IntegerField(null=True, verbose_name='Уставка аварийная (min)'),
        ),
        migrations.AlterField(
            model_name='bearing',
            name='temperature_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='bearing',
            name='temperature_warning_max',
            field=models.IntegerField(null=True, verbose_name='Уставка предупреждения (max)'),
        ),
        migrations.AlterField(
            model_name='bearing',
            name='temperature_warning_min',
            field=models.IntegerField(null=True, verbose_name='Уставка предупреждения (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='temperature_alarm_max',
            field=models.IntegerField(null=True, verbose_name='Уставка аварийная (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='temperature_alarm_min',
            field=models.IntegerField(null=True, verbose_name='Уставка аварийная (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='temperature_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='temperature_warning_max',
            field=models.IntegerField(null=True, verbose_name='Уставка предупреждения (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='temperature_warning_min',
            field=models.IntegerField(null=True, verbose_name='Уставка предупреждения (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_axial_alarm_max',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка аварийная (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_axial_alarm_min',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка аварийная (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_axial_value',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Вибрация Осевая'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_axial_warning_max',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка предупреждения (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_axial_warning_min',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка предупреждения (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_horizontal_alarm_max',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка аварийная (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_horizontal_alarm_min',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка аварийная (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_horizontal_value',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Вибрация Осевая'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_horizontal_warning_max',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка предупреждения (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_horizontal_warning_min',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка предупреждения (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_vertical_alarm_max',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка аварийная (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_vertical_alarm_min',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка аварийная (min)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_vertical_warning_max',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка предупреждения (max)'),
        ),
        migrations.AlterField(
            model_name='bearingextended',
            name='vibration_vertical_warning_min',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True, verbose_name='Уставка предупреждения (min)'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='oil_temperature_after',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Температура масла после охладителя'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='oil_temperature_before',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Температура масла до охладителя'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='water_temperature_after',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Температура воды на выходе охладителя'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='water_temperature_before',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Температура воды до охладителя'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='gas_collector_temperature_before',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Температура перед эксгаустером'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='gas_collector_underpressure_before',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Разрежение перед эксгаустером'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='gas_valve_closed',
            field=models.BooleanField(null=True, verbose_name='ЗАКРЫТО задвижка газ эксгаустер'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='gas_valve_open',
            field=models.BooleanField(null=True, verbose_name='ОТКРЫТО задвижка газ эксгаустер'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='gas_valve_position',
            field=models.IntegerField(null=True, verbose_name='Положение задвижки газ эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='main_drive_rotor_current',
            field=models.IntegerField(null=True, verbose_name='Ток ротора эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='main_drive_rotor_voltage',
            field=models.IntegerField(null=True, verbose_name='Напряжение ротора эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='main_drive_stator_current',
            field=models.IntegerField(null=True, verbose_name='Ток статора эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='main_drive_stator_voltage',
            field=models.IntegerField(null=True, verbose_name='Напряжение статора эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='oilsystem_oil_level',
            field=models.IntegerField(null=True, verbose_name='Уровень масла в маслосистеме эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='oilsystem_oil_pressure',
            field=models.IntegerField(null=True, verbose_name='Давление масла в маслосистеме эксгаустера'),
        ),
        migrations.AlterField(
            model_name='exhauster',
            name='work_status',
            field=models.BooleanField(null=True, verbose_name='Работа эксгаустера'),
        ),
    ]
