# Generated by Django 4.1.7 on 2023-02-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BearingExtendedObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_value', models.CharField(max_length=32, verbose_name='Температура')),
                ('temperature_alarm_max', models.CharField(max_length=32, verbose_name='Уставка аварийная (max)')),
                ('temperature_alarm_min', models.CharField(max_length=32, verbose_name='Уставка аварийная (min)')),
                ('temperature_warning_max', models.CharField(max_length=32, verbose_name='Уставка предупреждения (max)')),
                ('temperature_warning_min', models.CharField(max_length=32, verbose_name='Уставка предупреждения (min)')),
                ('vibration_axial_value', models.CharField(max_length=32, verbose_name='Вибрация Осевая')),
                ('vibration_axial_alarm_max', models.CharField(max_length=32, verbose_name='Уставка аварийная (max)')),
                ('vibration_axial_alarm_min', models.CharField(max_length=32, verbose_name='Уставка аварийная (min)')),
                ('vibration_axial_warning_max', models.CharField(max_length=32, verbose_name='Уставка предупреждения (max)')),
                ('vibration_axial_warning_min', models.CharField(max_length=32, verbose_name='Уставка предупреждения (min)')),
                ('vibration_horizontal_value', models.CharField(max_length=32, verbose_name='Вибрация Горизонтальная')),
                ('vibration_horizontal_alarm_max', models.CharField(max_length=32, verbose_name='Уставка аварийная (max)')),
                ('vibration_horizontal_alarm_min', models.CharField(max_length=32, verbose_name='Уставка аварийная (min)')),
                ('vibration_horizontal_warning_max', models.CharField(max_length=32, verbose_name='Уставка предупреждения (max)')),
                ('vibration_horizontal_warning_min', models.CharField(max_length=32, verbose_name='Уставка предупреждения (min)')),
                ('vibration_vertical_value', models.CharField(max_length=32, verbose_name='Вибрация Вертикальная')),
                ('vibration_vertical_alarm_max', models.CharField(max_length=32, verbose_name='Уставка аварийная (max)')),
                ('vibration_vertical_alarm_min', models.CharField(max_length=32, verbose_name='Уставка аварийная (min)')),
                ('vibration_vertical_warning_max', models.CharField(max_length=32, verbose_name='Уставка предупреждения (max)')),
                ('vibration_vertical_warning_min', models.CharField(max_length=32, verbose_name='Уставка предупреждения (min)')),
            ],
            options={
                'verbose_name': 'Подшипник расширенный',
                'verbose_name_plural': 'Подшипники расширенные',
            },
        ),
        migrations.CreateModel(
            name='ExhausterObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название эксгаустера')),
                ('gas_collector_temperature_before', models.CharField(max_length=32, verbose_name='Температура перед эксгаустером')),
                ('gas_collector_underpressure_before', models.CharField(max_length=32, verbose_name='Разрежение перед эксгаустером')),
                ('gas_valve_closed', models.CharField(max_length=32, verbose_name='ЗАКРЫТО задвижка газ эксгаустер')),
                ('gas_valve_open', models.CharField(max_length=32, verbose_name='ОТКРЫТО задвижка газ эксгаустер')),
                ('gas_valve_position', models.CharField(max_length=32, verbose_name='Положение задвижки газ эксгаустера')),
                ('main_drive_rotor_current', models.CharField(max_length=32, verbose_name='Ток ротора эксгаустера')),
                ('main_drive_rotor_voltage', models.CharField(max_length=32, verbose_name='Напряжение ротора эксгаустера')),
                ('main_drive_stator_current', models.CharField(max_length=32, verbose_name='Ток статора эксгаустера')),
                ('main_drive_stator_voltage', models.CharField(max_length=32, verbose_name='Напряжение статора эксгаустера')),
                ('oilsystem_oil_level', models.CharField(max_length=32, verbose_name='Уровень масла в маслосистеме эксгаустера')),
                ('oilsystem_oil_pressure', models.CharField(max_length=32, verbose_name='Давление масла в маслосистеме эксгаустера')),
                ('work_status', models.CharField(max_length=32, verbose_name='Работа эксгаустера')),
                ('bearing_ext_eight', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_eight', to='datamanager.bearingextendedobj', verbose_name='Подшипник 8')),
                ('bearing_ext_one', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_one', to='datamanager.bearingextendedobj', verbose_name='Подшипник 1')),
                ('bearing_ext_seven', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_seven', to='datamanager.bearingextendedobj', verbose_name='Подшипник 7')),
                ('bearing_ext_two', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_ext_two', to='datamanager.bearingextendedobj', verbose_name='Подшипник 2')),
            ],
            options={
                'verbose_name': 'Эксгаустер',
                'verbose_name_plural': 'Эксгаустеры',
            },
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_ext_eight',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_ext_one',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_ext_seven',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_ext_two',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_five',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_four',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_nine',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_six',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='bearing_three',
        ),
        migrations.RemoveField(
            model_name='exhauster',
            name='cooler',
        ),
        migrations.RenameModel(
            old_name='Bearing',
            new_name='BearingObj',
        ),
        migrations.RenameModel(
            old_name='Cooler',
            new_name='CoolerObj',
        ),
        migrations.DeleteModel(
            name='BearingExtended',
        ),
        migrations.DeleteModel(
            name='Exhauster',
        ),
        migrations.AddField(
            model_name='exhausterobj',
            name='bearing_five',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_five', to='datamanager.bearingobj', verbose_name='Подшипник 5'),
        ),
        migrations.AddField(
            model_name='exhausterobj',
            name='bearing_four',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_four', to='datamanager.bearingobj', verbose_name='Подшипник 4'),
        ),
        migrations.AddField(
            model_name='exhausterobj',
            name='bearing_nine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_nine', to='datamanager.bearingobj', verbose_name='Подшипник 9'),
        ),
        migrations.AddField(
            model_name='exhausterobj',
            name='bearing_six',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_six', to='datamanager.bearingobj', verbose_name='Подшипник 6'),
        ),
        migrations.AddField(
            model_name='exhausterobj',
            name='bearing_three',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bearing_three', to='datamanager.bearingobj', verbose_name='Подшипник 3'),
        ),
        migrations.AddField(
            model_name='exhausterobj',
            name='cooler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='datamanager.coolerobj', verbose_name='Охладитель'),
        ),
    ]
